spring:
  profiles:
    active: guo

# MinIO 配置
minio:
  endpoint: http://10.111.43.55:9000      # MinIO服务地址
  fileHost: http://10.111.43.55:9000      # 文件地址host
  bucketName: img                      # 存储桶bucket名称
  accessKey: admin                         # 用户名
  secretKey: 12345678                     # 密码
  imgSize: 1024                           # 图片大小限制，单位：m
  fileSize: 1024                          # 文件大小限制，单位：m


